owner: Syahreza-Ferdian # Your GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository

sites:
  - name: Personal Website
    url: https://syahreza.site

  - name: VPS
    check: "tcp-ping"
    url: $HOST
    port: $PORT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "This website is powered by Upptime"
  introMessage: "Used to monitor the uptime of my personal website"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
